# Google App Engine configuration for React Vite app
runtime: nodejs20

# Instance class for performance
instance_class: F2

# Environment variables
env_variables:
  NODE_ENV: production

# Static file handlers for React build
handlers:
  # Handle static assets
  - url: /assets
    static_dir: dist/assets
    secure: always

  # Handle favicon and other static files in public
  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|css|js|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(ico|png|jpg|jpeg|gif|svg|css|js|woff|woff2|ttf|eot)$
    secure: always

  # Handle all other routes with index.html (for React Router)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6